library(testthat)
library(excerno)
library(vcfR)
library(BSgenome)
library(BSgenome.Hsapiens.UCSC.hg38)
library(stringr)
library(tidyverse)
library(R.utils)
library(BSgenome.Hsapiens.UCSC.hg38,)
library(MutationalPatterns)
library(Biostrings)
library(GenomicRanges)

test_check("excerno")
